---
- block:
    - name: Update apt-get repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Upgrade all apt packages
      apt:
        upgrade: dist
        force_apt_get: yes

    - name: Clean apt packages
      apt:
        autoremove: yes
        autoclean: yes
        purge: yes

    - name: Enable unattended upgrades
      apt:
        name: unattended-upgrades
        state: present
        update_cache: yes
    
    - name: dfdfdf
      template: 20auto-upgrades.j2
      owner: root
    
    - name: dfdfdf
      template: 20auto-upgrades.j2
      owner: root
    
    

  become: yes
